[package]
name = "mml-cli"
description = "CLI to compile MML messages to MIME messages and interpret MIME messages as MML messages"
version = "1.0.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["command-line-utilities", "email", "text-processing"]
keywords = ["email", "mime", "message", "mml", "emacs"]
homepage = "https://pimalaya.org/mml/"
documentation = "https://pimalaya.org/mml/"
repository = "https://github.com/soywod/mml/"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[bin]]
name = "mml"
path = "src/main.rs"

[features]
default = [
  "compiler",
  "interpreter",
  #"pgp-commands",
  #"pgp-gpg",
  #"pgp-native",
]
compiler = ["dep:ariadne", "mml-lib/compiler"]
interpreter = ["mml-lib/interpreter"]
pgp-commands = ["mml-lib/pgp-commands"]
pgp-gpg = ["mml-lib/pgp-gpg"]
pgp-native = ["mml-lib/pgp-native"]

[dependencies]
color-eyre = "0.6"
ariadne = { version = "0.3", optional = true }
atty = "0.2"
clap = { version = "4.3", features = ["derive"] }
clap_complete = "4.3"
clap_mangen = "0.2"
tracing = "0.1"
pimalaya-tui = { version = "=0.1", default-features = false, features = ["path", "cli", "tracing"] }
mml-lib = { version = "1", default-features = false }
tokio = { version = "1.32", default-features = false, features = ["macros", "rt-multi-thread"] }

[patch.crates-io]
mml-lib = { git = "https://github.com/pimalaya/core" }
pimalaya-tui = { git = "https://github.com/pimalaya/tui" }
