[package]
name = "mml-cli"
description = "CLI to deal with Emacs MIME message Meta Language (MML)."
version = "0.2.1"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["command-line-utilities", "email", "text-processing"]
keywords = ["email", "mime", "message", "mml", "emacs"]
homepage = "https://pimalaya.org/"
documentation = "https://pimalaya.org/mml/"
repository = "https://github.com/soywod/mml/"
metadata.docs.rs.all-features = true

[[bin]]
name = "mml"
path = "src/main.rs"

[features]
all = ["compiler", "interpreter", "pgp-commands", "pgp-gpg", "pgp-native"]
default = ["compiler", "interpreter"]
compiler = ["mml-lib/compiler", "ariadne"]
interpreter = ["mml-lib/interpreter"]
pgp-commands = ["mml-lib/pgp-commands"]
pgp-gpg = ["mml-lib/pgp-gpg"]
pgp-native = ["mml-lib/pgp-native"]

[dev-dependencies.tempfile]
version = "3.3"

# error

[dependencies.anyhow]
version = "1.0"

# log

[dependencies.log]
version = "0.4"

[dependencies.env_logger]
version = "0.10"

# async

[dependencies.tokio]
version = "1.32"
default-features = false
features = ["macros", "rt-multi-thread"]

# io

[dependencies.atty]
version = "0.2"

[dependencies.shellexpand-utils]
version = "0.1.0"

# cli

[dependencies.clap]
version = "4.3"
features = ["derive"]

[dependencies.clap_complete]
version = "4.3"

[dependencies.clap_mangen]
version = "0.2"

# mml

[dependencies.ariadne]
version = "0.3.0"
optional = true

[dependencies.mml-lib]
version = "=0.3.2"
default-features = false
