[package]
name = "mml-cli"
description = "CLI to deal with Emacs MIME message Meta Language (MML)."
version = "0.2.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["command-line-utilities", "email", "text-processing"]
keywords = ["email", "mime", "message", "mml", "emacs"]
homepage = "https://pimalaya.org/"
documentation = "https://pimalaya.org/mml/"
repository = "https://github.com/soywod/mml/"
metadata.docs.rs.all-features = true

[[bin]]
name = "mml"
path = "src/main.rs"

[features]
default = ["compiler", "interpreter"]
compiler = ["mml-lib/compiler"]
interpreter = ["mml-lib/interpreter"]
pgp = ["mml-lib/pgp"]
pgp-commands = ["mml-lib/pgp-commands"]
pgp-gpg = ["mml-lib/pgp-gpg"]
pgp-native = ["mml-lib/pgp-native"]

[dev-dependencies.tempfile]
version = "3.3"

# error
[dependencies.anyhow]
version = "1.0"

# log
[dependencies.log]
version = "0.4"

[dependencies.env_logger]
version = "0.10"

# async
[dependencies.tokio]
version = "1.32"
default-features = false
features = ["fs", "io-util", "io-std", "macros", "rt-multi-thread"]

# io
[dependencies.atty]
version = "0.2"

[dependencies.shellexpand]
version = "3.1"

# cli
[dependencies.clap]
version = "4.3"

[dependencies.clap_complete]
version = "4.3"

[dependencies.clap_mangen]
version = "0.2"

# mml
[dependencies.mml-lib]
version = "=0.2.0"
default-features = false
